### ISSUE TITLE
Hydrator interface

### ISSUE THREAD

**Issue by TemirkhanN** [samdark/hydrator#4]
Can you explain why'd you prefer interface

hydrate(array $data, string $objectClass): object;
hydrateInto(array $data, $object): object;

?

**Comment by samdark** [comment]
What are alternatives?

**Comment by TemirkhanN** [comment]
Kind of

hydrate(array $data, $object): void;

**Comment by samdark** [comment]
Ah, got the question now. Hydration into class exists because when you're getting a new object you want to avoid calling constructor.

**Comment by TemirkhanN** [comment]
I can not  suppose why should hydrator do that?

**Comment by samdark** [comment]
For example, Entity should generate its own UUID what you should not be able to set yourself either via setter or via constructor.

**Comment by TemirkhanN** [comment]
For some reason I am not agree with some moments. Still issue has been resolved)
