### ISSUE TITLE
Map в аргументах

### ISSUE THREAD

**Issue by brussens** [samdark/hydrator#7]
Собственно вопрос, почему бы не сделать передачу map в сами методы, вместо конструктора? Если использовать в качестве сервиса объявленного через DI, имея единственный инстанс нет возможности закидывать разные map.

**Comment by brussens** [comment]
Могу пулл если что кинуть

**Comment by TemirkhanN** [comment]
Ну, такая идея, на самом деле. Мапинг все-таки к конфигурации, а конфигурацию ты подаешь из какого-нибудь сервис-контейнера или стороннего вспомогательного сервиса - то бишь, тебе все равно придется для каждого отдельного объекта заводить некую "фабрику", которая будет инстанциировать отдельный гидратор под этот самый объект. Или же устраивать грязь в коде, где ты будешь доставать из шляпы волшебника информацию о мапинге того или иного объекта и гонять ее по коду. В лучшем случае из последнего кейса получится размазывание одной цельной процедуры на несколько отдельных(так мы нарушим [High cohesion)](https://ru.wikipedia.org/wiki/GRASP#5._%D0%92%D1%8B%D1%81%D0%BE%D0%BA%D0%B0%D1%8F_%D1%81%D0%B2%D1%8F%D0%B7%D0%BD%D0%BE%D1%81%D1%82%D1%8C_(High_Cohesion)[2]), а в худшем разведется копипаста маппинга на разных участках кода(гидрации и дегидрации).

**Comment by samdark** [comment]
Всё так.
